[package]
name = "safe_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
# tempfile is used in tests; keep as dev-dependency too
tempfile = "3"

[dev-dependencies]
tempfile = "3"
